export { default as Navbar } from "./navbar/Navbar";
export { default as Header } from "./header/Header";
export { default as Brands } from "./brands/Brands";
export { default as Feature } from "./feature/Feature";
export { default as Blog } from "./blog/Blog";
export { default as CTA } from "./cta/CTA";
export { default as WhatGPT3 } from "./whatGPT3/WhatGPT3";
export { default as Footer } from "./footer/Footer";
export { default as Features } from "./features/Features";
